In [9]:
import array as ar
arr = ar.array('i',[2,6,1,0,9,12])
print("Newly created array: ",end="")
for i in range(0,6):
  print(arr[i],end=" ")

Newly created array: 2 6 1 0 9 12 

In [11]:
import pandas as pd
dict = {'Name':['Sam','Ram','Raj','Bob'],'Age':[23,25,56,78]}
df = pd.DataFrame(dict,index=[True,False,True,False])
print(df)
print("Accessing data frame using boolean index:-")
print(df.loc[True])

      Name  Age
True   Sam   23
False  Ram   25
True   Raj   56
False  Bob   78
Accessing data frame using boolean index:-
     Name  Age
True  Sam   23
True  Raj   56


In [21]:
import numpy as np
arr = np.arange(10)
print("The Original array is: ",arr,end=" ")

arr=np.arange(10).reshape(2,5)
print("\nReshaped array with 2 rows and 5 columns:")
print(arr)
print("\nReshaped array with 5 rows and 2 columns:")
arr=np.arange(10).reshape(5,2)
print(arr)

The Original array is:  [0 1 2 3 4 5 6 7 8 9] 
Reshaped array with 2 rows and 5 columns:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped array with 5 rows and 2 columns:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
